# FROM node:18

# WORKDIR /app

# COPY ./package*.json ./

# RUN npm install

# COPY . .

# CMD [ "npm", "start" ]

FROM node:18-alpine
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
CMD ["npm", "start"]

# FROM node:14.16.1

# WORKDIR /app

# COPY package.json ./ 

# RUN npm install

# COPY . .

# EXPOSE 3000

# CMD ["npm", "start"]`