services:      
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile.backend.local
    volumes:
      - ./backend/upload:/upload
      - ./backend/assets:/assets
    ports: 
      - 4000:4000
      - 27017:27017
    environment: 
      - PORT=4000
      - MONGO_HOST=host.docker.internal
      - MONGO_PORT=27017
      - MONGO_USER=bookingSRV
      - MONGO_PASS=password
      - MONGO_DB_NAME=bookingdb
      - UPLOAD_DEST=./upload
      - JWT_SECRET_KEY=secret
      - JWT_EXPIRATION_TIME=1h
      - JWT_SECRET_KEY_REFRESH_TOKEN=secretrefresh
      - JWT_EXPIRATION_TIME_REFRESH_TOKEN=1d
      - COOKIES_EXPIRATION_TIME=8.64e+7
    # expose: 
    #   - 4000
    networks:
      - backend
    # develop:
    #   watch:
    #     - action: sync

  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.frontend.local
    ports: 
      - 80:3000
    volumes:
      - ./frontend:/app
    environment: 
      - REACT_APP_SERVER_HOST=localhost
      - REACT_APP_SERVER_PORT=4000
    depends_on:
      - backend
    networks:
      - backend
    # stdin_open: true
    # tty: true
    # develop:
    #   watch:
    #     - action: sync

networks:
    backend:
      driver: bridge