# FROM node:18-alpine
# RUN mkdir -p /svr/app
# WORKDIR /svr/app
# RUN npm i -g @nestjs/cli --silent
# COPY package.json .
# COPY package-lock.json .
# RUN npm install --silent
# COPY . .
# # Value set in .env file.
# EXPOSE $PORT
# CMD ["npm", "run", "start:debug"]

FROM node:18

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

# EXPOSE 4000

CMD [ "npm", "run", "start:dev" ]